version: '3'
services:
  db:
    image: postgres:10
    container_name: pgfedesoft_api
    volumes:
      - ../dockerdata/dbdata/etc:/etc/postgresql
      - ../dockerdata/dbdata/log:/var/log/postgresql
      - ../dockerdata/dbdata/pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: railsfedesoft_api
    command: bundle exec puma
    volumes:
      - .:/myapp
      - ../dockerdata/data/bundle:/bundle
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle
    depends_on:
      - db
